// <auto-generated />
using System;
using Imobiliaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Imobiliaria.Migrations
{
    [DbContext(typeof(ImobiContext))]
    partial class ImobiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Imobiliaria.Models.Imovel", b =>
                {
                    b.Property<int>("ImovelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImovelID"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImovelID");

                    b.ToTable("Imovel", (string)null);
                });

            modelBuilder.Entity("Imobiliaria.Models.Residente", b =>
                {
                    b.Property<int>("ResidenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidenteID"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidenteID");

                    b.ToTable("Residente", (string)null);
                });

            modelBuilder.Entity("Imobiliaria.Models.ResidenteImovel", b =>
                {
                    b.Property<int>("ResidenteID")
                        .HasColumnType("int");

                    b.Property<int>("ImovelID")
                        .HasColumnType("int");

                    b.HasKey("ResidenteID", "ImovelID");

                    b.HasIndex("ImovelID");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("Imobiliaria.Models.ResidenteImovel", b =>
                {
                    b.HasOne("Imobiliaria.Models.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imobiliaria.Models.Residente", "Residente")
                        .WithMany()
                        .HasForeignKey("ResidenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");

                    b.Navigation("Residente");
                });
#pragma warning restore 612, 618
        }
    }
}
